language: go

go:
  - "1.14.x"

install:
  - go install -v ./...

script:
  # Fast-fail on non-zero exit codes
  - set -e
  # Verify that all files have been gofmt'd with simplification.
  - diff <(gofmt -l -s ./) <(printf "")
  # Verify that unit tests pass
  - go test -v ./...

notifications:
  slack:
    secure: NWDRfVMFLg2DIssh/I5IY569rdSbNcLUpBX8+8aUPkSLH7eu+GDpV93MIe7sjWmWCzzz6KfqvT0nDB990cNSTPhDB2aaVwmXHK9PsuXjsH/Qoz8D1uIofV5xRYH5lmmpEplYCYSlO1cWsI8YJZvCRr1m/1x5LirKNBWOsmHBLcsD1E2SMdZxz24cjELXqsohJRMK2Bh9MrbLdmHtOWXwA89CZue1sbSBj1eNwGcVkwe87ihKDsyB3ctT6sK34UHSBmIdO/KY8T3d1CXhLWUX7sM3q65xteJ5lWmLcVigdft0AInLpOgjnafdKzJey0xGrXPVqsVlbsDv5cG/DlVG5OKQyUnl7/p9KY1qhghGg22GRtQ+HEIoF9f8KiqvBdBECuvUADM+xm2lmjGw/QL71bGDkCtoM3O7Q+/LT0qHb1TFBgCzKgM8Db3pitNevDTkRN1X824YpJtFv8kOXABM5sVj5G9CzPdbakXgX7FBU0hDcPRaFpztgxLECHulhseXbTMo5RFn0BuVP+jagoptKlAojdMQKoBZ/Y+HPwpJueS5sU4E9r8CkL/s3Ct+7AZpCifaDCv3FWJs8DBb1DgfQLaiNqlj6sHjTThDrl+ddHktpyunv/uB30Gvx/z4HIA2JVxheUaJO5fc17ZWr2UotnyI6b9TZgfMQ1G9HMPIGGk=
